# data is a volume-only container for keeping the postgres and alfresco filesystem
# volumes in one place.
data:
    image: hwgonz/postgres_datastore
db:
    image: postgres
    environment:
#        - MYSQL_ROOT_PASSWORD=mage
        - POSTGRES_USER=alfresco
        - POSTGRES_PASSWORD=alfresco
#        - MYSQL_DATABASE=mage
    volumes_from:
        - data
#php:
#    image: kojiromike/magento_php
#    links:
#        - db
#    volumes_from:
#        - data
#    ports:
#        - "9000:9000"
#web:
#    image: kojiromike/magento_nginx
#    links:
#        - php
#    ports:
#        - "80:80"
#    volumes_from:
#        - data
#fs:
#    image: kojiromike/magento_fs
#    volumes_from:
#        - data
#    ports:
#        - "137:137"
#        - "138:138"
#        - "139:139"
#        - "445:445"
